[build]
  # Base directory for the build
  base = "."
  
  # Build command
  command = "npm run build"
  
  # Publish directory (where the built files are located)
  publish = "dist/public"
  
  # Functions directory
  functions = "netlify/functions"

[build.environment]
  # Set Node.js version
  NODE_VERSION = "18"

# Redirects for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin" 